# Numpy Indexing & Slicing

## Indexing

In [1]:
a_list = [[1,2,3],['a','b','c']]
a_list[1][1]

'b'

In [2]:
import numpy as np

In [3]:
a_arr = np.array([[1,2,3],[4,5,6]])
a_arr[1][1]

5

In [4]:
a_arr[1,1]   # 행(row),열(cloumn)

5

## Slicing

In [5]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],int)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a[:2,:2]

array([[1, 2],
       [5, 6]])

In [7]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [8]:
a[1:,1:-1]

array([[ 6,  7],
       [10, 11]])

In [9]:
a[0:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [10]:
a[1:,0::2]

array([[ 5,  7],
       [ 9, 11]])