 ## List와 넘파이 어레이 속도 비교

In [21]:
import numpy as np
np_arr = np.arange(10000)

In [23]:
nu_list = []
for i in range(10000):
    nu_list.append(i)
#nu_list = [i for i in range(10000)]

In [24]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 17 ms


In [26]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 8.98 ms


### 1차원 배열(array) 만들기

In [29]:
vector = np.array([1,4,7,10], float)
vector

array([ 1.,  4.,  7., 10.])

In [30]:
type(vector)

numpy.ndarray

In [31]:
vector.shape

(4,)

### 2차원 배열 만들기

In [34]:
matrix  = np.array([[1,2,5,8],[2,3,4,9],[4,5,6,7]])
matrix

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [35]:
matrix.shape

(3, 4)

### 3차원 배열 만들기

In [36]:
t_list = [[[1,2,5,8],[2,3,4,9],[4,5,6,7]],
            [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
            [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
            [[1,2,5,8],[2,3,4,9],[4,5,6,7]]]
tensor = np.array(t_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [37]:
tensor.shape

(4, 3, 4)

## Array shape

### ndim & size

In [39]:
vector.ndim, matrix.ndim, tensor ndim

(1, 2, 3)