# Numpy operation

In [3]:
import numpy as np

In [4]:
test_array = np.arange(1,11)
test_array.sum()

55

In [5]:
test_array.sum(dtype=np.float)

55.0

## axis

In [6]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
matrix.sum()

36

In [8]:
matrix.sum(axis=0) # 행

array([ 9, 12, 15])

In [9]:
matrix.sum(axis=1) # 열

array([ 3, 12, 21])

## mean & std (평균 및 표준편차)

In [10]:
matrix.mean()

4.0

In [11]:
matrix.mean(axis=0)

array([3., 4., 5.])

In [12]:
# Standard deviation
matrix.std()

2.581988897471611

In [13]:
matrix.std().round(4) # 반올림 소숫점 이하 4자리

2.582

## Mathematical functions

In [14]:
matrix = np.arange(9).reshape(3,3)
np.exp(matrix)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

## Concatenate(Array를 합치는 함수)

In [15]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [16]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [17]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.hstack((a,c))

array([[1, 2, 0, 1, 2],
       [3, 4, 3, 4, 5]])

In [21]:
np.concatenate((a,c),axis=1)

array([[1, 2, 0, 1, 2],
       [3, 4, 3, 4, 5]])

In [22]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## operations between arrays

In [23]:
a+a

array([[2, 4],
       [6, 8]])

In [24]:
a-a

array([[0, 0],
       [0, 0]])

In [25]:
# element-wise multiplication
a*a

array([[ 1,  4],
       [ 9, 16]])

## dot product

In [26]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
b = np.arange(6).reshape(2,3)  # b = a.T
b

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a.dot(b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [29]:
b.dot(a)

array([[10, 13],
       [28, 40]])

In [30]:
np.dot(a,b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

## Broadcasting (Shape 이 다른 배열간 연산)

In [31]:
scalar = 3  # 사칙연산 전부 가능
a + scalar

array([[3, 4],
       [5, 6],
       [7, 8]])

In [32]:
a * scalar

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [33]:
d = np.arange(10,21,10)
d

array([10, 20])

In [34]:
a + d

array([[10, 21],
       [12, 23],
       [14, 25]])

In [37]:
e = np.arange(10,41,10).reshape(2,-1)
e

array([[10, 20],
       [30, 40]])

In [38]:
a + e  # 행 or 열의 개수가 안맞으면 연산 불가

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 