# Numpy creation

## arange

In [1]:
import numpy as np

In [2]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [3]:
list(range(0,5,0.5)).tolist()

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
np.arange(0,5,0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

## ones, zeros and empty

In [8]:
np.zeros(shape=(10,), dtype=np.int8)
# 원소 10개인 벡터 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [12]:
np.ones((2,5))  # 2 x 5  - 값이 1인 matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((3,5))  # 메모리가 초기화 되어있지 않음
# shape 만 주어지고 비어있는 ndarray 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Something like

In [16]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)
# 기존 ndarray의 shape 크기만큼 0,1을 반환

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [18]:
np.empty_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Identity (단위행렬)

In [19]:
np.identity(n=3, dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## eye (대각선이 1인 행렬)

In [22]:
np.eye(3,5, dtype=int)  # float

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [23]:
np.eye(3,5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(3,5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

## diag (대각 행렬의 값을 추출)

In [28]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [29]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.diag(matrix, k=1)

array([1, 5])

## Random sampling
### 0~1사이의 난수

In [31]:
np.random.seed(2021)

In [32]:
np.random.uniform(0,1,10).reshape(2,5)   # 균등분포 (최소,최대,개수)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [33]:
np.random.normal(0,1,10).reshape(2,5)  # 정뷰분포 (평균,표준편차,개수)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])