# Numpy Comparision

In [1]:
import numpy as np 

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a >5), np.all(a >5)

(True, False)

In [5]:
np.any(a > 20), np.all(a <20)

(False, True)

## Logical operation

In [7]:
a = np.array([1,3,0],float)
b = np.logical_and(a>0, a<3)  # 0 < a < 3
b

array([ True, False, False])

In [9]:
c = np.logical_or(a<0, a>3)  # a < 0 or a > 3
c

array([False, False, False])

In [10]:
np.where(a > 0)   # 조건식에 맞는 인덱스값 출력

(array([0, 1], dtype=int64),)

In [11]:
## Nan --> Not a Number, np.NaN 
## Inf --> Infinite, np.Inf 
x = np.array([1, np.NaN, np.Inf])
x

array([ 1., nan, inf])

In [12]:
np.isnan(x)

array([False,  True, False])

In [13]:
np.isnan(x).sum()

1

In [23]:
X = np.arange(100, dtype=np.float)
X[50] = np.NaN

In [24]:
np.isnan(X)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [25]:
np.isnan(X).sum()

1

In [26]:
np.isfinite(x)

array([ True, False, False])

In [27]:
len(x) - np.isfinite(x).sum()

2

## argmax & argmin  (최대/최소의 인덱스값 출력)

In [30]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [31]:
np.argmax(a)  # 최대값이 있는 인덱스값

5

In [32]:
np.argmin(a)  # 최소값이 있는 인덱스값

0

In [33]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [34]:
np.argmax(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [36]:
np.argmin(a, axis=1)

array([0, 2, 3], dtype=int64)