# Numpy Boolean and fancy index

In [1]:
import numpy as np 

## Boolean index

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array[test_array > 3]  # filter

array([4., 8., 9., 7.])

In [4]:
condition = test_array > 3
test_array[condition]

array([4., 8., 9., 7.])

## Fancy Index

In [5]:
a = np.arange(2,9,2)
a

array([2, 4, 6, 8])

In [6]:
b = np.array([0,2,1,3,0,2], dtype = np.int32)
b

array([0, 2, 1, 3, 0, 2])

In [7]:
a[b]

array([2, 6, 4, 8, 2, 6])

In [8]:
c = np.array([0,2,1,3,4,2], dtype = np.int32)
a[c]  # a에 인덱스가 4인값이 없어 오류!

IndexError: index 4 is out of bounds for axis 0 with size 4