## 연습문제

In [2]:
import numpy as np 

In [3]:
#1
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#2
vec = np.arange(49,9,-1) # vector[::-1]
vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [5]:
#3
q=np.zeros(shape=(10), dtype=np.int8)
q[4]=1
q
# np.eye(1,10,k=4)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

In [6]:
#4
k = np.arange(9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#5
vector1 = np.array([1,2,0,0,4,0])
vector1[vector1>0]  # vector1[vector != 0]

array([1, 2, 4])

In [8]:
#6
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#7
a = np.random.random((3,3))
a, np.max(a), np.min(a)
# np.random.uniform(0,1,9).reshape(3,3)

(array([[0.48693673, 0.99465977, 0.95826439],
        [0.01154456, 0.38438237, 0.25852974],
        [0.69118711, 0.3676553 , 0.58581759]]),
 0.9946597704965439,
 0.01154456353526545)

In [10]:
#8
a = np.random.random((3,3))
a, a.mean(axis=0), a.mean(axis=1)

(array([[0.48805278, 0.70002005, 0.14995546],
        [0.83551745, 0.37287738, 0.01131766],
        [0.0830588 , 0.49119542, 0.64621277]]),
 array([0.46887634, 0.52136428, 0.26916196]),
 array([0.44600943, 0.40657083, 0.40682233]))

In [11]:
#9
one = np.eye(5,k=1)
one

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [12]:
two = 2*np.eye(5)
two

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [13]:
three = 3*np.eye(5,k=-1)
three

array([[0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.]])

In [14]:
one + two + three

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])