## 연습문제

In [1]:
import numpy as np 

In [2]:
#1
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
#2
vec = np.arange(49,9,-1)
vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [50]:
#3
q=np.zeros(shape=(10), dtype=np.int8)
q[4]=1
q

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

In [35]:
#4
k = np.arange(9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#5
vector1 = np.array([1,2,0,0,4,0])
vector1[vector1>0]

array([1, 2, 4])

In [6]:
#6
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#7
a = np.random.random((3,3))
a, np.max(a), np.min(a)

(array([[0.86691845, 0.10320553, 0.11251112],
        [0.780134  , 0.13504883, 0.12855847],
        [0.24050317, 0.2918108 , 0.33323648]]),
 0.8669184474887572,
 0.10320552704938357)

In [48]:
#8
a = np.random.random((3,3))
a, a.mean(axis=0), a.mean(axis=1)

(array([[0.01944854, 0.94681664, 0.1633732 ],
        [0.02743246, 0.97902348, 0.18486651],
        [0.83445623, 0.01227522, 0.03366613]]),
 array([0.29377908, 0.64603844, 0.12730195]),
 array([0.37654613, 0.39710748, 0.29346586]))